### ISSUE TITLE
richiesta tutorial creare script

### ISSUE THREAD

**Issue by skull1** [Robotex/KAADIVVVV#12]
Ciao, fantastico lavoro con questo script.
La mia richiesta e' se potresti creare una guida per come creare questo genere di script, tipo come trovare dove la pagina web si accorge che stai usando un adblocker, come creare lo script per bloccarlo etc..
E' da un po' che mi interessa fare una cosa del genere per altri siti oltre a vvvid, ma non ho trovato tutorial o indizi soddifacenti...

**Comment by Robotex** [comment]
Ciao e grazie per i complimenti!
Non esiste una guida universale per creare questo genere di script, si tratta di analizzare il codice con strumenti che mette a disposizione il browser stesso (debugger e console javascript per la maggior parte) e utilizzare tecniche di ingegneria inversa per capire la logica che sta dietro al codice ad ogni aggiornamento, dopo aver capito come funziona scrivere lo script è la parte più semplice e si utilizza di solito JavaScript in quanto è il linguaggio risconosciuto universalmente da tutti i browser.
Se ti incuriosisce il campo, puoi provare a leggere qualche manuale di JavaScript per neofiti, per farti un'idea se la programmazione può piacerti oppure no :)
