### ISSUE TITLE
Non funziona più?

### ISSUE THREAD

**Issue by DarkLiuke** [Robotex/KAADIVVVV#14]
Sembra che vvvvid abbia aggiornato il proprio sistema di anti adblock

**Comment by ghost** [comment]
Ho anche io lo stesso problema,  ti sarei grato se trovi un modo per bypassarlo ancora :)

**Comment by Robotex** [comment]
Risolto nella 1.1.2

**Comment by ghost** [comment]
Grazie sei il migliore :D
