### ISSUE TITLE
Non funziona più :(

### ISSUE THREAD

**Issue by Antonz256** [Robotex/KAADIVVVV#16]
Come da titolo, non blocca più le pubblicità, dopo la musichetta iniziale quando si apre il sito subito mi porta alla pagina che ti invita a togliere l'adblock, grazie in anticipo

**Comment by Killua99x** [comment]
confermo, non funziona più, stessa identica cosa di @Antonz256

**Comment by Michele5485** [comment]
Mi aggiungo alla lista, non va più nemmeno a me e ormai è diventato indispensabile. Spero che venga sistemato presto...

**Comment by jspenguin2017** [comment]
I only speak English, I have some technical details to share, hopefully it will be useful. 

This script was totally working yesterday but not anymore today. I checked the `vvvvid` object and the first thing I noticed is that `cab3` is renamed to `cab4`. But the current script, even with the property name changed, still does not work. Soon, I noticed that `window.vvvvid.models.PlayerObj.prototype.initializePlayer` has a strange line: 
```js
if (vvvvid[OnjHgy7kJH]) {
    window.location = nmd2TGh6Fs;
}
```

Out of curiosity, I locked `window.OnjHgy7kJH` and surprisingly, it breaks the whole website. Something is fishy here, so I patched that prototype function but it still redirects me. This is what I have so far, does not really work yet...
<details>

```js
                "use strict";
                if (window.vvvvid) {
                    const re1 = /if\(vvvvid\[[a-zA-Z0-9]+]\){window\.location=[a-zA-Z0-9]+}/;
                    const data1 = "";
                    const re2 = /var a=function\(\){.*};/;
                    const data2 = `var a=function(){vvvvid.advPlayer=null,$(c.playerControlsClass).removeClass("ppad"),d()};`;
                    //Patch properties
                    window.vvvvid.cab4 = function (a, b) {
                        this.isAdBlockActive = false;
                        if (b) {
                            b(false);
                            //window.setTimeout(b.bind(this, false), 5);
                        }
                    };
                    window.Object.defineProperty(window.vvvvid, "thereIsAdv", {
                        configurable: false,
                        set() { },
                        get() {
                            return false;
                        },
                    });
                    window.eval("window.vvvvid.models.PlayerObj.prototype.initializePlayer = " +
                        window.String(window.vvvvid.models.PlayerObj.prototype.initializePlayer).replace(re1, data1));
                    window.eval("window.vvvvid.models.PlayerObj.prototype.startAdv = " +
                        window.String(window.vvvvid.models.PlayerObj.prototype.startAdv).replace(re2, data2));
                }
```

</details>

I will let you know if I found something else.

**Comment by Umb3** [comment]
Confermo, funzionava oggi pomeriggio, ora non più :/

@jspenguin2017 ty for the effort

**Comment by Robotex** [comment]
I've just pushed the release 1.2.0 to development branch and will commit it now to master, give it some time to propagate to the distribution sites.

@jspenguin2017 
Thanks for the details, I've already decoded it a few hours ago but I wasn't home to push the changes.

**Comment by jspenguin2017** [comment]
I see this line in your code: 
```js
window[mnsJHnyT] = window.vvvvid.models.PlayerObj.prototype.startAdv;
```
Is there a possibility that the variable name is randomized daily?

**Comment by jspenguin2017** [comment]
I can confirm that it works now, just that random variable name feels like a trap.

**Comment by Robotex** [comment]
@jspenguin2017 
I don't believe so, at least in this version they added encryption to obfuscate it probably to delay me from reverse engineering it. In fact, I believe they are aware of the existence of this script and only encrypted the attribute names I used in the previous release (they are even checking for existence of cab3), and left everything else in clear text.

**Comment by jspenguin2017** [comment]
Hopefully... 
This is going to be a long battle... Anyway, awesome project, keep it up 👍

**Comment by jspenguin2017** [comment]
Oh, `window.OnjHgy7kJH` is `"cab3"`, this makes sense now.
