### ISSUE TITLE
Can the "Register Now to continue watching" screen be bypassed?

### ISSUE THREAD

**Issue by beppe9000** [Robotex/KAADIVVVV#18]
Qualcuno sa se è server-side ?

**Comment by Robotex** [comment]
Ad intuito dovrebbe essere possibile, ma ha poco a che fare con lo scopo di questo userscript e al momento non ho in programma di scriverne altri

**Comment by beppe9000** [comment]
Ok. Avevo chiesto perchè mi stavo appropinquando io a produrre qualcosa del genere ma dato che mi sembrava che avessi una certa famigliarità con vvvvid volevo vedere se è una causa persa in principio...
