### ISSUE TITLE
Episode page keeps refreshing

### ISSUE THREAD

**Issue by fra42** [Robotex/KAADIVVVV#21]
With firefox quantum (57.0) + ublock origin + tampermonkey when I watch an episode of something (tried both anime and tv shows) the page keeps refreshing (I can see the "view count" increasing) and so I can't see the video. This do not happens when I try to watch movies.

 Thanks for your work and support!

**Comment by Robotex** [comment]
Are you able to check if the same issue happens on Chrome browser?

**Comment by fra42** [comment]
Tried again with both browser (same Firefox & Chrome), no problem. I wonder what happened...

Thanks for the support and for the awesome project!
