### ISSUE TITLE
Per semplificare...

### ISSUE THREAD

**Issue by ItalianApkDownloader** [Robotex/KAADIVVVV#22]
cambiandolo così funziona direttamente senza attivare la pubblicità

window.vvvvid.models.PlayerObj.prototype.startAdv = function (a, b, c) {
    c();
};

**Comment by Robotex** [comment]
Non ricordo precisamente il motivo per cui strutturai il codice così siccome sono passati quasi due anni da quando lo analizzai, ma ad intuito penso che ci furono dei casi in cui l'overlay veniva creato altrove nel codice e senza i vari destroy rimaneva tutto bloccato, inoltre è/era una prevenzione in più da aggirare se avessero cambiato il codice.
Magari adesso non serve più, ma siccome per ora funziona ancora non sento la necessità di cambiarlo, ti ringrazio per il suggerimento e ne terrò conto se dovessero rilasciare un ulteriore aggiornamento!

**Comment by Robotex** [comment]
Risolto in #25
