### ISSUE TITLE
Non pare funzionarere

### ISSUE THREAD

**Issue by cyberkimera** [Robotex/KAADIVVVV#23]
A quanto pare ci deve essere qualche problema...

**Comment by Robotex** [comment]
Quale browser ed estensioni utilizzi?
Io su Chrome+uBlock Origin+Tampermonkey non noto problemi

**Comment by cyberkimera** [comment]
Ciao, ho fatto dei test su computer diversi con questi settings.
Chrome, AdblockPlus, Tampermonkey e KAADIVVVV
Risultato= Le finestre non rispondevano/non si aprivano
Mozilla, AdblockPlus, Greasemonkey e KAADIVVVV
Risultato= Le finestre non rispondevano/non si aprivano

Alla fine pare io abbia risolto su Mozilla, sostituendo con queste lines

window.vvvvid.models.PlayerObj.prototype.startAdv = function (a, b, c) {
c();
};

Mentre su Chrome risulta che io debba aggiornarare Flash Player (cosa non vera);
Lascio aperto il thread ancora per un po' in caso riscontrassi altri problemi di sorta!

**Comment by Robotex** [comment]
Risolto in #25
