### ISSUE TITLE
Non va più

### ISSUE THREAD

**Issue by xMultiB** [Robotex/KAADIVVVV#30]
A quanto pare hanno fatto un aggiornamento di vvvvid e adesso con adblock+ublock origin+script installato con tampermonkey viene rilevato e rimanda ad una pagina di errore.

**Comment by Robotex** [comment]
Io con Chrome+uBlock origin+Tampermonkey+KAADIVVVV 1.3.1 non riesco riesco a riprodurre il tuo problema, per caso stai utilizzando le ultime versioni?

**Comment by xMultiB** [comment]
Si ho tutto aggiornato, il problema si verifica quando vado a riprodurre un episodio, se riesco dopo ti metto uno screen

**Comment by xMultiB** [comment]
Strano, ho provato adesso con gli stessi settaggi di ieri sera ed è andato, ti metto comunque la foto dell'errore che mi ha dato ieri sera, dovesse ricapitare ti riscrivo.
https://imgur.com/a/pZ6gc8i

**Comment by Robotex** [comment]
Può succedere che a seguito di qualche aggiornamento dello script manager o di chrome stesso salti qualcosa ed è già successo in passato, chiudo la issue se non ci sono ulteriori segnalazioni.
