### ISSUE TITLE
Schermata nera

### ISSUE THREAD

**Issue by genesx** [Robotex/KAADIVVVV#36]
dev'essere cambiato qualcosa nel modo in cui VVVID gestisce il controllo anti adblock, perché ora su Chrome, utilizzando lo script con Tampermonkey, il sito mi dà solo una pagina nera. Riattivare in qualunque momento Tampermonkey e adblock anche dopo aver provato a disattivarli, aver aperto la pagina e averli riattivati dopo un paio di spot causa di nuovo schermo nero.

**Comment by xlollomanx** [comment]
io ho risolto ricaricando la pagina anche se a differenza tua uso violentmonkey

**Comment by Robotex** [comment]
Ho provato entrambi Tampermonkey e Violentmonkey su Chrome ma non noto il problema, i video mi partono normalmente

**Comment by genesx** [comment]
Ho fatto alcune prove, e disattivando tutti gli script e riattivando solo KAADIVVV sono riuscito a farlo funzionare normalmente, quindi penso che si fosse verificato un conflitto fra script (mai successo prima, probabilmente l'aggiornamento di uno script ha "rotto" l'equilibrio).
Chiedo scusa per non aver verificato prima questa eventualità, mea culpa!
