### ISSUE TITLE
VVVVID stuck on black page

### ISSUE THREAD

**Issue by CynroDrake** [Robotex/KAADIVVVV#39]
The script stopped working since june/may, whatever i do when i open the vvvvid page stays black, i can navigate the menù but nothing works, already tried to remove and reinstall everything, many many times, nothing worked so far, any solutions?

**Comment by Robotex** [comment]
A new update was released one month ago, what version of the script are you using?

**Comment by CynroDrake** [comment]
The last one 1.5.0

**Comment by CynroDrake** [comment]
just noticed you are italian, quindi possiamo cambiare lingua

**Comment by Robotex** [comment]
Browser e script manager utilizzato?

**Comment by Robotex** [comment]
In un precedente issue che un altro utente ha creato nello stesso periodo da te indicato https://github.com/Robotex/KAADIVVVV/issues/36#issuecomment-506935622 qualcuno aveva avuto lo stesso problema e ha indicato la soluzione che ha trovato, forse potrebbe essere collegato con il tuo problema

**Comment by CynroDrake** [comment]
uso tamper monkey su google chrome,uso solo il tuo script e ho provato anche altri ma nulla

**Comment by Robotex** [comment]
Ho appena fatto una prova su Chrome (78.0.3904.108) e Tampermonkey (4.8.41) e non riscontro problemi, potresti provare a disconnetterti dall'account nel sito e riloggarti?
Se il problema continua a persistere ho bisogno che mi incolli qui ciò che appare nella console javascript (da Mac si accede dal menù di Chrome Visualizza->Opzioni per sviluppatori->Console JavaScript)

**Comment by CynroDrake** [comment]
non cambia nulla, resta comunque tutto nero ( http://prntscr.com/q1fn39 ), non appaiono errori java, come apro da windows?

**Comment by xlollomanx** [comment]
Anche a me funziona senza problemi. Hai provato per caso a disabilitare l'adblocker su vvvid? Magari è qualche filtro che crea qualche problema

**Comment by CynroDrake** [comment]
già provato

**Comment by CynroDrake** [comment]
trovata una soluzione, a quanto pare è il popup blocker che gli da fastidio, nonostante lo avessi sempre usato, grazie comunque per aver cercato di aiutare!
