### ISSUE TITLE
Lo script non funziona

### ISSUE THREAD

**Issue by XwX404** [Robotex/KAADIVVVV#40]
Uso KADIVVVV da tanto e questa è la prima volta che non funziona. Dopo la schermata del ''play'' di vvvvid, quando seleziono un episodio, vengo portato alla pagina di rilevazione di AdBlockPlus: che faccio? (ho abp, detection bypass e lo script)

**Comment by regrog** [comment]
confermo, nemmeno a me funziona più

**Comment by yethie** [comment]
Sviluppando (e usando) questo script procurate un danno ad un'azienda italiana che da anni si batte per portare in Italia animazione in forma gratuita e legale. Forse non ve ne rendete conto ma l'unico risultato che queste attività illecite otterranno è quello di lasciare l'animazione in mano alla pirateria e ai servizi a pagamento.

**Comment by XwX404** [comment]
> Sviluppando (e usando) questo script procurate un danno ad un'azienda italiana che da anni si batte per portare in Italia animazione in forma gratuita e legale. Forse non ve ne rendete conto ma l'unico risultato che queste attività illecite otterranno è quello di lasciare l'animazione in mano alla pirateria e ai servizi a pagamento.

ne sono cosciente, appena potrò permettermi l'abbonamento a vvvvid sarò più che felice di farlo. Che poi, sei venuto a commentare sotto un issue solo per dire questo? da quel che dici, non dovresti usare kadivvvv... :/
mi chiedo solo perchè tu abbia commentato per farci la morale, non voglio assolutamente litigare anche perchè so che hai ragione

**Comment by regrog** [comment]
Io personalmente ho provato di tutto per disabilitare adblock come dicono e tenere la pubblicità ma anche disabilitato non va mai VVVVID.
Non mi sono mai lamentato della pubblicità, però così è inusabile.

**Comment by Robotex** [comment]
Fixed with 1.6.0
Anche se non mi risultava, probabilmente i filtri di easylist hanno risolto prima di me

**Comment by tiorisig** [comment]
Sembra non funzionare nuovamente
