### ISSUE TITLE
Versione aggiornata ma vedo comunque le pubblicità

### ISSUE THREAD

**Issue by Sombry** [Robotex/KAADIVVVV#42]
Salve non sono molto pratico quindi probabilmente ho sbagliato qualcosa:
Ho scaricato la 1.6.0 ma mi dava comunque la pagina ad-block di vvvvid, dopo un po di test ho notato che l'estenzione che scatenava tutto era quella di duckduckgo.
Tolgo l'estenzione e gli adblock e ora vvvvid va (urra) ma le pubblicita mi vengono mostrate comunque anche se ho KAADIVVVV attivo su greasemonkey.
Magari sbaglio qualcosa o servono piu estenzioni in simultamea per far funzionare tutto(?)

ringrazio tutti in anticipo

**Comment by Robotex** [comment]
Ciao, lo script ha lo solo scopo di permettere di continuare ad utilizzare le estensioni di adblocking (esempio uBlock Origin o AdBlock Plus) senza doverli disattivare, quindi se non ne hai uno continuerà a mostrarti la pubblicità

**Comment by Sombry** [comment]
risolto.
A quanto pare (almeno nel mio caso) l'unica estensione che per ora non mi manda nel sito di ad-block di vvvvid e uBlock Origin , usare duckduckgo con la protezione tracker o un altra (qualsiasi) estensione ad-block non funziona.
Ti ringrazio Robotex per avermi consigliato uBlock
