### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by quiet-and-falling** [Robotex/KAADIVVVV#47]
Da un paio di settimane lo script non funziona, ho visto che anche altre persone hanno avuto il mio stesso problema, ma non sono riuscito a risolvere
![image](https://user-images.githubusercontent.com/74802789/99864898-5f65ba80-2ba6-11eb-9607-63021548e51e.png)

**Comment by Robotex** [comment]
Ho appena approvato l'aggiornamento 1.6.1, provalo e fammi sapere se succede ancora

**Comment by quiet-and-falling** [comment]
Funziona, grazie mille dell'aiuto
