### ISSUE TITLE
KADIVVV not working

### ISSUE THREAD

**Issue by akun90** [Robotex/KAADIVVVV#49]
Today the scrip doesnt work anymore, i keep getting blocked on vvvid.it
i tried to disable, adblock plus, adbloc, ublock and so on... unless you disable all adblocker you cant get it to work

**Comment by martiscolo** [comment]
same there

**Comment by Robotex** [comment]
Updated script to 1.6.2, re-open this if it still doesn't work

**Comment by lordmarte** [comment]
Lo scritp kaadivvvv va in conflitto con lo script anti adblocker. Quindi la
gente crede che sia per colpa di adblock ma non è cosi. Rimuovendo quello
script dovrebbe funzionare tutto, anche perché è diventato inutile visto
che ora tutti gli adblocker hanno esso al proprio interno di default.

Il lun 30 nov 2020, 16:52 akun90 <notifications@github.com> ha scritto:

**Comment by akun90** [comment]
still problems even after updating to 1.6.2

**Comment by martiscolo** [comment]
ho eliminato tutti gli altri script e sia con adblock che senza la pubblicità continua ad apparire
