### ISSUE TITLE
Non funziona!

### ISSUE THREAD

**Issue by jyj52** [Robotex/KAADIVVVV#50]
Dal nuovo aggiornamento VVVVID  continua a darmi le pubblicità. Ho già aggiornato alla nuova versione, ma non cambia nulla.

**Comment by akun90** [comment]
Still not working even after updating to 1.6.2

**Comment by xDado99x** [comment]
Yeah unfortunately it's still not working even after 1.6.2. Hope you can solve it soon:)

**Comment by Robotex** [comment]
Fixed in 1.7.0
