### ISSUE TITLE
Problema con VVVVID

### ISSUE THREAD

**Issue by Someone0011** [Robotex/KAADIVVVV#55]
ho installato il nuovo codice, ma adesso vvvvid mi da schermata nera, senza player.

**Comment by martiscolo** [comment]
hanno bloccato di nuovo lo script. piuttosto che sorbirmi 7 pubblicità ad episodio preferisco non usare  vvvvid

**Comment by martiscolo** [comment]
> hanno bloccato di nuovo lo script. piuttosto che sorbirmi 7 pubblicità ad episodio preferisco non usare vvvvid

Grazie ai tempestivi update funziona di nuovo :') (non avevo visto)

**Comment by akun90** [comment]
broken again.

**Comment by Robotex** [comment]
Fixed in 1.7.2
