### ISSUE TITLE
Non funziona più

### ISSUE THREAD

**Issue by seutetchi** [Robotex/KAADIVVVV#56]
persiste il problema oggi, ho installato l'aggiornamento oggi ma continua a non funzionare

![image](https://user-images.githubusercontent.com/75478988/101155586-9ff21900-3627-11eb-9ddc-e11284a7a477.png)
![image](https://user-images.githubusercontent.com/75478988/101155604-a7192700-3627-11eb-9ba5-7818d2bf227f.png)

**Comment by akun90** [comment]
yeah broken again

**Comment by Robotex** [comment]
Fixed in 1.7.2
