### ISSUE TITLE
Lo script non funziona più

### ISSUE THREAD

**Issue by TheDarkLordo** [Robotex/KAADIVVVV#59]
Ad oggi 20/12/20, gli spot pubblicitari appaiono comunque anche con lo script attivo e aggiornato

**Comment by Sjnod** [comment]
Anche a me

**Comment by Fren62** [comment]
anche a me

**Comment by Lifix46** [comment]
ad oggi 22/12/ 20 non funziona ancora, con adblocker e script attivo, vvvvid si blocca perché vede adblocker attivo e non fa proseguire alla visione dell'episodio.

**Comment by Fren62** [comment]
a me non va anche con adblocker spento

**Comment by Robotex** [comment]
Risolto nella 1.7.4

**Comment by TheDarkLordo** [comment]
Grazie tante!

**Comment by Sjnod** [comment]
Bel lavoro!
