### ISSUE TITLE
Lo script non funziona

### ISSUE THREAD

**Issue by Lu0z** [Robotex/KAADIVVVV#61]
Ciao Robotex, devono aver modificato di nuovo il codice della pagina e lo script è nuovamente K.O.

Volevo chiederti una cosa: ho visto le modifiche che esegui allo script quando lo aggiorni, solitamente è un cambio di codice in un determinato script. 
è possibile sapere in quale punto riesci a recuperare questi valori? sarei interessato a capirne di più e magari imparare a modificare autonomamente la mia copia dello script. è una cosa che vorrei imparare solo per piacere personale :)

**Comment by Lifix46** [comment]
già, script di nuovo k.o

**Comment by Meitalody** [comment]
> Ciao Robotex, devono aver modificato di nuovo il codice della pagina e lo script è nuovamente K.O.
> 
> Volevo chiederti una cosa: ho visto le modifiche che esegui allo script quando lo aggiorni, solitamente è un cambio di codice in un determinato script.
> è possibile sapere in quale punto riesci a recuperare questi valori? sarei interessato a capirne di più e magari imparare a modificare autonomamente la mia copia dello script. è una cosa che vorrei imparare solo per piacere personale :)

Effettua le seguenti modifiche:
Line 36:
**this.play8Ads = false;** modificala mettendo **this.play9Ads = false;**
Line 46 & 52:
cambia **'jheowldjh'** in **'jheboadjh'**

**Comment by Lu0z** [comment]
> > Ciao Robotex, devono aver modificato di nuovo il codice della pagina e lo script è nuovamente K.O.
> > Volevo chiederti una cosa: ho visto le modifiche che esegui allo script quando lo aggiorni, solitamente è un cambio di codice in un determinato script.
> > è possibile sapere in quale punto riesci a recuperare questi valori? sarei interessato a capirne di più e magari imparare a modificare autonomamente la mia copia dello script. è una cosa che vorrei imparare solo per piacere personale :)
> 
> Effettua le seguenti modifiche:
> Line 36:
> **this.play8Ads = false;** modificala mettendo **this.play9Ads = false;**
> Line 46 & 52:
> cambia **'jheowldjh'** in **'jheboadjh'**

Grazie mille, mi piacerebbe comunque capire da dove estrapolate questi codici, apro la sorgente  della pagina ma non riesco a beccarli. usate per caso qualche app specifica che sniffa il traffico? mi è parso di capire da delle vecchie issues che c'è di mezzo una criptazione.

**Comment by Meitalody** [comment]
@Lu0z
Tutto ciò che ho fatto è aprire la sorgente della pagina e cercare "checkAdv" da li ho preso il nuovo codice.
Credo cambi ogni volta che aggiornano il sito, ad esempio in questi giorni hanno aggiunto la funzionalità GIF
Sicuramente Robotex ne saprà di più, io sono solo un semplice utente :)

**Comment by Robotex** [comment]
> Ciao Robotex, devono aver modificato di nuovo il codice della pagina e lo script è nuovamente K.O.
> 
> Volevo chiederti una cosa: ho visto le modifiche che esegui allo script quando lo aggiorni, solitamente è un cambio di codice in un determinato script.
> è possibile sapere in quale punto riesci a recuperare questi valori? sarei interessato a capirne di più e magari imparare a modificare autonomamente la mia copia dello script. è una cosa che vorrei imparare solo per piacere personale :)

Essendo lo script open source, così come è semplice modificarlo lo è anche leggerlo per renderlo ineffettivo in una continua rincorsa tra gatto e topo e so che i ragazzi che ci lavorano danno un'occhiata spesso qua, ci sarebbero anche opzioni ed algoritmi alternativi di più lunga durata ma essendo un progetto che era nato come supporto a FADIVVVV ed ora non più necessario, mantengo questo progetto a tempo perso ed ultimamente non ne ho molto, perciò quando possibile preferisco accettare PR per comodità (oltretutto non guardo più gli anime lì, mi sono spostato su altre piattaforme a pagamento). 

Per la tua domanda su dove guardare, @sevenvoodoo ha già risposto dove trovare un punto di partenza, il file ha lo stesso nome del sito, se hai dimestichezza con javascript e un po' di passione per l'ingegneria inversa non ti sarà difficile individuare i pezzi chiave

**Comment by Lu0z** [comment]
> @Lu0z
> Tutto ciò che ho fatto è aprire la sorgente della pagina e cercare "checkAdv" da li ho preso il nuovo codice.
> Credo cambi ogni volta che aggiornano il sito, ad esempio in questi giorni hanno aggiunto la funzionalità GIF
> Sicuramente Robotex ne saprà di più, io sono solo un semplice utente :)

Ho aperto la sorgente della pagina ma con la ricerca nono sono riuscito a trovare la riga, mi dice zero elementi corrispondono alla ricerca. forse sbaglio qualcosa...

mi sapresti indicare qual'è la pagina esatta in cui devo essere?

**Comment by nixxo** [comment]
https://static.vvvvid.it/js/vvvvid.js
