### ISSUE TITLE
Non funziona più ma i codici non sono variati

### ISSUE THREAD

**Issue by Lu0z** [Robotex/KAADIVVVV#67]
Ciao, pare che lo script non funzioni più. ho controllato per un nuovo codice ma pare sia rimasto lo stesso, sarà stata implementata qualche nuova funzione? mi confermate che anche a voi non va?

**Comment by pacho94** [comment]
Anche a me stessa cosa

**Comment by Robotex** [comment]
Non riesco a riprodurre il problema, lo fa con tutti i video?

**Comment by jokull7** [comment]
Stesso problema non mi funziona più

**Comment by Lu0z** [comment]
> Non riesco a riprodurre il problema, lo fa con tutti i video?

nonappena entro nel sito, parte la intro con il logo e poi mi manda sulla pagina anti-adblocker

**Comment by bvcx1** [comment]
anche a me da lo stesso problema

**Comment by MatBomber** [comment]
Io ho provato a cambiare 'jhenobdjh' in 'sdhdfygfjk' e sembra funzionarmi, spero possa esservi utile

**Comment by Robotex** [comment]
> Io ho provato a cambiare 'jhenobdjh' in 'sdhdfygfjk' e sembra funzionarmi, spero possa esservi utile

Aggiornato nella 1.7.8, grazie
