### ISSUE TITLE
Funziona a tratti

### ISSUE THREAD

**Issue by gloddo** [Robotex/KAADIVVVV#9]
A volte funziona, a volte bisogna ricaricare la pagina per farlo funzionare. In particolare alla pubblicità in mezzo non funziona quasi mai. Ho letto lo script.. è molto semplice, meglio di tanti altri pieni di chissà che robaccia. Bravo!

**Comment by Robotex** [comment]
Scusa per il ritardo nella risposta ma mi sono accorto solo ora della notifica!
Effettivamente non ho provato a vedermi degli episodi interi, nel loro ultimo aggiornamento hanno inserito un contatore direttamente sul codice che carica le pubblicità e mi sono regolato sui primi minuti di un episodio a caso, ho appena caricato ora una modifica al valore iniziale con un numero arbitrariamente grande e spero non succeda più il problema.
Fammi sapere!

**Comment by gloddo** [comment]
Guarda, ancora non va, ma forse è leggermente meglio di prima. Ti avverto comunque che in automatico non viene scaricata la versione 1.0.4a, ma la 1.0.4 (uso chrome con tampermonkey).

**Comment by Robotex** [comment]
Proverò a far andare un po' di episodi e vedo se mi esce.
Per restringere il campo di ricerca, succede solitamente a inizio/metà/fine episodio? Ti reindirizza sempre alla pagina adblock.html?
Riguardo la versione grazie per la segnalazione, a quanto pare ho interpretato male la documentazione e 1.0.4a/b/c viene considerato più vecchio di 1.0.4, provvederò ad utilizzare il numero corretto dalla prossima release

**Comment by gloddo** [comment]
Mmm allora.. Sempre adblock.html, e mi appare o al break pubblicitario a metà episodio, o quando passo ad un episodio successivo cliccando sulla freccia a destra. Per risolverlo devo ricaricare la pagina e posizionarmi subito dopo la pubblicità (nel caso dell'interruzione centrale).

**Comment by Robotex** [comment]
Credo di essere riuscito a riprodurre il problema, vedo se riesco ad aggirare la procedura causante.
Nell'attesa, puoi provare la [1.0.3c](https://github.com/Robotex/KAADIVVVV/blob/5e218dc24e10a7135e309468e8b2e0734ff43170/kaadivvvv.user.js) che in teoria dovrebbe disattivare alla radice il controllo, l'ho tenuto da parte come fix tampone.

**Comment by Robotex** [comment]
Ho rilasciato la nuova versione che non dovrebbe più dare fastidi ne di aggiornamento ne di redirect, se ci sono altri problemi riapri liberamente questo issue oppure aprine uno nuovo.
Ciao!
